-- Create aac_cards table
CREATE TABLE IF NOT EXISTS public.aac_cards (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    slug text NOT NULL,
    label text NOT NULL,
    category text NOT NULL,
    emoji text NOT NULL,
    image_path text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(slug, category)
);

-- Enable RLS
ALTER TABLE public.aac_cards ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Enable read access for all users" ON public.aac_cards
    FOR SELECT USING (true);

-- Grant access to authenticated and anon users
GRANT SELECT ON public.aac_cards TO authenticated;
GRANT SELECT ON public.aac_cards TO anon;

-- Insert data
INSERT INTO public.aac_cards (slug, label, category, emoji, image_path) VALUES
-- Animal Cards
('animal', '동물', 'animal', '🐾', 'muru-cards/AAC-cards/illustration/animal/aac_animal.png'),
('ant', '개미', 'animal', '🐜', 'muru-cards/AAC-cards/illustration/animal/aac_ant.png'),
('bear', '곰', 'animal', '🐻', 'muru-cards/AAC-cards/illustration/animal/aac_bear.png'),
('bee', '벌', 'animal', '🐝', 'muru-cards/AAC-cards/illustration/animal/aac_bee.png'),
('bird', '새', 'animal', '🐦', 'muru-cards/AAC-cards/illustration/animal/aac_bird.png'),
('bug', '벌레', 'animal', '🐛', 'muru-cards/AAC-cards/illustration/animal/aac_bug.png'),
('butterfly', '나비', 'animal', '🦋', 'muru-cards/AAC-cards/illustration/animal/aac_butterfly.png'),
('calf', '송아지', 'animal', '🐄', 'muru-cards/AAC-cards/illustration/animal/aac_calf.png'),
('cat', '고양이', 'animal', '🐱', 'muru-cards/AAC-cards/illustration/animal/aac_cat.png'),
('chick', '병아리', 'animal', '🐤', 'muru-cards/AAC-cards/illustration/animal/aac_chick.png'),
('chicken', '닭', 'animal', '🐔', 'muru-cards/AAC-cards/illustration/animal/aac_chicken.png'),
('cow', '소', 'animal', '🐄', 'muru-cards/AAC-cards/illustration/animal/aac_cow.png'),
('crocodile', '악어', 'animal', '🐊', 'muru-cards/AAC-cards/illustration/animal/aac_crocodile.png'),
('deer', '사슴', 'animal', '🦌', 'muru-cards/AAC-cards/illustration/animal/aac_deer.png'),
('dinosaur', '공룡', 'animal', '🦕', 'muru-cards/AAC-cards/illustration/animal/aac_dinosaur.png'),
('dog', '강아지', 'animal', '🐶', 'muru-cards/AAC-cards/illustration/animal/aac_dog.png'),
('donkey', '당나귀', 'animal', '🫏', 'muru-cards/AAC-cards/illustration/animal/aac_donkey.png'),
('duck', '오리', 'animal', '🦆', 'muru-cards/AAC-cards/illustration/animal/aac_duck.png'),
('elephant', '코끼리', 'animal', '🐘', 'muru-cards/AAC-cards/illustration/animal/aac_elephant.png'),
('fish', '물고기', 'animal', '🐟', 'muru-cards/AAC-cards/illustration/animal/aac_fish.png'),
('fox', '여우', 'animal', '🦊', 'muru-cards/AAC-cards/illustration/animal/aac_fox.png'),
('frog', '개구리', 'animal', '🐸', 'muru-cards/AAC-cards/illustration/animal/aac_frog.png'),
('giraffe', '기린', 'animal', '🦒', 'muru-cards/AAC-cards/illustration/animal/aac_giraffe.png'),
('goat', '염소', 'animal', '🐐', 'muru-cards/AAC-cards/illustration/animal/aac_goat.png'),
('goose', '거위', 'animal', '🪿', 'muru-cards/AAC-cards/illustration/animal/aac_goose.png'),
('hippo', '하마', 'animal', '🦛', 'muru-cards/AAC-cards/illustration/animal/aac_hippo.png'),
('horse', '말', 'animal', '🐴', 'muru-cards/AAC-cards/illustration/animal/aac_horse.png'),
('lion', '사자', 'animal', '🦁', 'muru-cards/AAC-cards/illustration/animal/aac_lion.png'),
('monkey', '원숭이', 'animal', '🐵', 'muru-cards/AAC-cards/illustration/animal/aac_monkey.png'),
('mouse', '쥐', 'animal', '🐭', 'muru-cards/AAC-cards/illustration/animal/aac_mouse.png'),
('owl', '부엉이', 'animal', '🦉', 'muru-cards/AAC-cards/illustration/animal/aac_owl.png'),
('penguin', '펭귄', 'animal', '🐧', 'muru-cards/AAC-cards/illustration/animal/aac_penguin.png'),
('pig', '돼지', 'animal', '🐷', 'muru-cards/AAC-cards/illustration/animal/aac_pig.png'),
('pigeon', '비둘기', 'animal', '🕊️', 'muru-cards/AAC-cards/illustration/animal/aac_pigeon.png'),
('rabbit', '토끼', 'animal', '🐰', 'muru-cards/AAC-cards/illustration/animal/aac_rabbit.png'),
('sheep', '양', 'animal', '🐑', 'muru-cards/AAC-cards/illustration/animal/aac_sheep.png'),
('snake', '뱀', 'animal', '🐍', 'muru-cards/AAC-cards/illustration/animal/aac_snake.png'),
('sparrow', '참새', 'animal', '🐦', 'muru-cards/AAC-cards/illustration/animal/aac_sparrow.png'),
('squirrel', '다람쥐', 'animal', '🐿️', 'muru-cards/AAC-cards/illustration/animal/aac_squirrel.png'),
('tiger', '호랑이', 'animal', '🐯', 'muru-cards/AAC-cards/illustration/animal/aac_tiger.png'),
('turtle', '거북이', 'animal', '🐢', 'muru-cards/AAC-cards/illustration/animal/aac_turtle.png'),

-- Food Cards
('apple', '사과', 'food', '🍎', 'muru-cards/AAC-cards/illustration/food/aac_apple.png'),
('banana', '바나나', 'food', '🍌', 'muru-cards/AAC-cards/illustration/food/aac_banana.png'),
('beans', '콩', 'food', '🫘', 'muru-cards/AAC-cards/illustration/food/aac_beans.png'),
('bread', '빵', 'food', '🍞', 'muru-cards/AAC-cards/illustration/food/aac_bread.png'),
('cake', '케이크', 'food', '🎂', 'muru-cards/AAC-cards/illustration/food/aac_cake.png'),
('candy', '사탕', 'food', '🍬', 'muru-cards/AAC-cards/illustration/food/aac_candy.png'),
('carrot', '당근', 'food', '🥕', 'muru-cards/AAC-cards/illustration/food/aac_carrot.png'),
('cheese', '치즈', 'food', '🧀', 'muru-cards/AAC-cards/illustration/food/aac_cheese.png'),
('chestnut', '밤', 'food', '🌰', 'muru-cards/AAC-cards/illustration/food/aac_chestnut.png'),
('chewing_gum', '껌', 'food', '🫧', 'muru-cards/AAC-cards/illustration/food/aac_chewing_gum.png'),
('chicken_meat', '닭고기', 'food', '🍗', 'muru-cards/AAC-cards/illustration/food/aac_chicken_meat.png'),
('chips', '감자칩', 'food', '🍟', 'muru-cards/AAC-cards/illustration/food/aac_chips.png'),
('chocolate', '초콜릿', 'food', '🍫', 'muru-cards/AAC-cards/illustration/food/aac_chocolate.png'),
('cider', '사이다', 'food', '🥤', 'muru-cards/AAC-cards/illustration/food/aac_cider.png'),
('coffee', '커피', 'food', '☕', 'muru-cards/AAC-cards/illustration/food/aac_coffee.png'),
('cola', '콜라', 'food', '🥤', 'muru-cards/AAC-cards/illustration/food/aac_cola.png'),
('corn', '옥수수', 'food', '🌽', 'muru-cards/AAC-cards/illustration/food/aac_corn.png'),
('daikon', '무', 'food', '🥬', 'muru-cards/AAC-cards/illustration/food/aac_daikon.png'),
('donut', '도넛', 'food', '🍩', 'muru-cards/AAC-cards/illustration/food/aac_donut.png'),
('egg', '계란', 'food', '🥚', 'muru-cards/AAC-cards/illustration/food/aac_egg.png'),
('fish', '생선', 'food', '🐟', 'muru-cards/AAC-cards/illustration/food/aac_fish.png'),
('food', '음식', 'food', '🍽️', 'muru-cards/AAC-cards/illustration/food/aac_food.png'),
('fruit', '과일', 'food', '🍎', 'muru-cards/AAC-cards/illustration/food/aac_fruit.png'),
('grape_green', '청포도', 'food', '🍇', 'muru-cards/AAC-cards/illustration/food/aac_grape_green.png'),
('grape_purple', '포도', 'food', '🍇', 'muru-cards/AAC-cards/illustration/food/aac_grape_purple.png'),
('hamburger', '햄버거', 'food', '🍔', 'muru-cards/AAC-cards/illustration/food/aac_hamburger.png'),
('hotdog', '핫도그', 'food', '🌭', 'muru-cards/AAC-cards/illustration/food/aac_hotdog.png'),
('hotteok', '호떡', 'food', '🥞', 'muru-cards/AAC-cards/illustration/food/aac_hotteok.png'),
('ice', '얼음', 'food', '🧊', 'muru-cards/AAC-cards/illustration/food/aac_ice.png'),
('ice_cream', '아이스크림', 'food', '🍦', 'muru-cards/AAC-cards/illustration/food/aac_ice_cream.png'),
('instant_ramen', '라면', 'food', '🍜', 'muru-cards/AAC-cards/illustration/food/aac_instant_ramen.png'),
('juice', '주스', 'food', '🧃', 'muru-cards/AAC-cards/illustration/food/aac_juice.png'),
('kimchi', '김치', 'food', '🥬', 'muru-cards/AAC-cards/illustration/food/aac_kimchi.png'),
('laver', '김', 'food', '🍙', 'muru-cards/AAC-cards/illustration/food/aac_laver.png'),
('mandarine', '귤', 'food', '🍊', 'muru-cards/AAC-cards/illustration/food/aac_mandarine.png'),
('meat', '고기', 'food', '🥩', 'muru-cards/AAC-cards/illustration/food/aac_meat.png'),
('melon', '멜론', 'food', '🍈', 'muru-cards/AAC-cards/illustration/food/aac_melon.png'),
('milk', '우유', 'food', '🥛', 'muru-cards/AAC-cards/illustration/food/aac_milk.png'),
('napa_cabbage', '배추', 'food', '🥬', 'muru-cards/AAC-cards/illustration/food/aac_napa_cabbage.png'),
('noodles', '국수', 'food', '🍜', 'muru-cards/AAC-cards/illustration/food/aac_noodles.png'),
('orange', '오렌지', 'food', '🍊', 'muru-cards/AAC-cards/illustration/food/aac_orange.png'),
('peach', '복숭아', 'food', '🍑', 'muru-cards/AAC-cards/illustration/food/aac_peach.png'),
('peanuts', '땅콩', 'food', '🥜', 'muru-cards/AAC-cards/illustration/food/aac_peanuts.png'),
('pizza', '피자', 'food', '🍕', 'muru-cards/AAC-cards/illustration/food/aac_pizza.png'),
('pumpkin', '호박', 'food', '🎃', 'muru-cards/AAC-cards/illustration/food/aac_pumpkin.png'),
('rice', '밥', 'food', '🍚', 'muru-cards/AAC-cards/illustration/food/aac_rice.png'),
('spaghetti', '스파게티', 'food', '🍝', 'muru-cards/AAC-cards/illustration/food/aac_spaghetti.png'),
('strawberry', '딸기', 'food', '🍓', 'muru-cards/AAC-cards/illustration/food/aac_strawberry.png'),
('sugar', '설탕', 'food', '🧂', 'muru-cards/AAC-cards/illustration/food/aac_sugar.png'),
('sweet_potato', '고구마', 'food', '🍠', 'muru-cards/AAC-cards/illustration/food/aac_sweet_potato.png'),
('tomato', '토마토', 'food', '🍅', 'muru-cards/AAC-cards/illustration/food/aac_tomato.png'),
('tteok', '떡', 'food', '🍡', 'muru-cards/AAC-cards/illustration/food/aac_tteok.png'),
('water', '물', 'food', '💧', 'muru-cards/AAC-cards/illustration/food/aac_water.png'),
('watermelon', '수박', 'food', '🍉', 'muru-cards/AAC-cards/illustration/food/aac_watermelon.png'),
('yogurt', '요거트', 'food', '🥛', 'muru-cards/AAC-cards/illustration/food/aac_yogurt.png'),

-- Clothes Cards
('clothes', '옷', 'clothes', '👕', 'muru-cards/AAC-cards/illustration/clothes/aac_clothes.png'),
('backpack', '책가방', 'clothes', '🎒', 'muru-cards/AAC-cards/illustration/clothes/aac_backpack.png'),
('bag', '가방', 'clothes', '👜', 'muru-cards/AAC-cards/illustration/clothes/aac_bag.png'),
('belt', '벨트', 'clothes', '🪢', 'muru-cards/AAC-cards/illustration/clothes/aac_belt.png'),
('button', '단추', 'clothes', '🔘', 'muru-cards/AAC-cards/illustration/clothes/aac_button.png'),
('cap', '모자(캡)', 'clothes', '🧢', 'muru-cards/AAC-cards/illustration/clothes/aac_cap.png'),
('coat', '코트', 'clothes', '🧥', 'muru-cards/AAC-cards/illustration/clothes/aac_coat.png'),
('diaper', '기저귀', 'clothes', '👶', 'muru-cards/AAC-cards/illustration/clothes/aac_diaper.png'),
('gloves', '장갑', 'clothes', '🧤', 'muru-cards/AAC-cards/illustration/clothes/aac_gloves.png'),
('hat', '모자', 'clothes', '👒', 'muru-cards/AAC-cards/illustration/clothes/aac_hat.png'),
('jumper', '점퍼', 'clothes', '🧥', 'muru-cards/AAC-cards/illustration/clothes/aac_jumper.png'),
('necklace', '목걸이', 'clothes', '📿', 'muru-cards/AAC-cards/illustration/clothes/aac_necklace.png'),
('pajama', '잠옷', 'clothes', '👚', 'muru-cards/AAC-cards/illustration/clothes/aac_pajama.png'),
('panty', '팬티', 'clothes', '🩲', 'muru-cards/AAC-cards/illustration/clothes/aac_panty.png'),
('pants', '바지', 'clothes', '👖', 'muru-cards/AAC-cards/illustration/clothes/aac_pants.png'),
('pocket', '주머니', 'clothes', '👖', 'muru-cards/AAC-cards/illustration/clothes/aac_pocket.png'),
('scarf', '목도리', 'clothes', '🧣', 'muru-cards/AAC-cards/illustration/clothes/aac_scarf.png'),
('shoes_man', '구두(남)', 'clothes', '👞', 'muru-cards/AAC-cards/illustration/clothes/aac_shoes_man.png'),
('shoes_woman', '구두(여)', 'clothes', '👠', 'muru-cards/AAC-cards/illustration/clothes/aac_shoes_woman.png'),
('shoes', '신발', 'clothes', '👟', 'muru-cards/AAC-cards/illustration/clothes/aac_shoes.png'),
('skirt', '치마', 'clothes', '👗', 'muru-cards/AAC-cards/illustration/clothes/aac_skirt.png'),
('sneakers', '운동화', 'clothes', '👟', 'muru-cards/AAC-cards/illustration/clothes/aac_sneakers.png'),
('socks', '양말', 'clothes', '🧦', 'muru-cards/AAC-cards/illustration/clothes/aac_socks.png');
