-- Add Verb (Action) Cards
-- Base path: muru-cards/AAC-cards/illustration/verb/

INSERT INTO public.aac_cards (slug, label, category, emoji, image_path) VALUES
('go_around', '다니다', 'verb', '🚶', 'muru-cards/AAC-cards/illustration/verb/aac_go_around_다니다.png'),
('drink', '마시다', 'verb', '🥤', 'muru-cards/AAC-cards/illustration/verb/aac_drink.png'),
('eat', '먹다', 'verb', '🍽️', 'muru-cards/AAC-cards/illustration/verb/aac_eat.png'),
('go', '가다', 'verb', '🚶', 'muru-cards/AAC-cards/illustration/verb/aac_go.png'),
('sleep', '자다', 'verb', '💤', 'muru-cards/AAC-cards/illustration/verb/aac_sleep.png'),
('study', '공부하다', 'verb', '📚', 'muru-cards/AAC-cards/illustration/verb/aac_study.png'),
('teach', '가르치다', 'verb', '👩‍🏫', 'muru-cards/AAC-cards/illustration/verb/aac_teach.png'),
('wash', '씻다', 'verb', '🧼', 'muru-cards/AAC-cards/illustration/verb/aac_wash.png'),
('play', '놀다', 'verb', '🛝', 'muru-cards/AAC-cards/illustration/verb/aac_play.png'),
('read', '읽다', 'verb', '📖', 'muru-cards/AAC-cards/illustration/verb/aac_read.png'),
('write', '쓰다', 'verb', '✍️', 'muru-cards/AAC-cards/illustration/verb/aac_write.png'),
('draw', '그리다', 'verb', '🎨', 'muru-cards/AAC-cards/illustration/verb/aac_draw.png'),
('sing', '노래하다', 'verb', '🎤', 'muru-cards/AAC-cards/illustration/verb/aac_sing.png'),
('dance', '춤추다', 'verb', '💃', 'muru-cards/AAC-cards/illustration/verb/aac_dance.png'),
('cook', '요리하다', 'verb', '🍳', 'muru-cards/AAC-cards/illustration/verb/aac_cook.png'),
('clean', '청소하다', 'verb', '🧹', 'muru-cards/AAC-cards/illustration/verb/aac_clean.png'),
('run', '뛰다', 'verb', '🏃', 'muru-cards/AAC-cards/illustration/verb/aac_run.png'),
('walk', '걷다', 'verb', '🚶', 'muru-cards/AAC-cards/illustration/verb/aac_walk.png'),
('swim', '수영하다', 'verb', '🏊', 'muru-cards/AAC-cards/illustration/verb/aac_swim.png'),
('fly', '날다', 'verb', '✈️', 'muru-cards/AAC-cards/illustration/verb/aac_fly.png'),
('jump', '점프하다', 'verb', '🕴️', 'muru-cards/AAC-cards/illustration/verb/aac_jump.png'),
('sit', '앉다', 'verb', '🪑', 'muru-cards/AAC-cards/illustration/verb/aac_sit.png'),
('stand', '서다', 'verb', '🧍', 'muru-cards/AAC-cards/illustration/verb/aac_stand.png'),
('wait', '기다리다', 'verb', '⏳', 'muru-cards/AAC-cards/illustration/verb/aac_wait.png'),
('meet', '만나다', 'verb', '🤝', 'muru-cards/AAC-cards/illustration/verb/aac_meet.png'),
('love', '사랑하다', 'verb', '❤️', 'muru-cards/AAC-cards/illustration/verb/aac_love.png'),
('like', '좋아하다', 'verb', '👍', 'muru-cards/AAC-cards/illustration/verb/aac_like.png'),
('hate', '싫어하다', 'verb', '👎', 'muru-cards/AAC-cards/illustration/verb/aac_hate.png'),
('cry', '울다', 'verb', '😢', 'muru-cards/AAC-cards/illustration/verb/aac_cry.png'),
('laugh', '웃다', 'verb', '😄', 'muru-cards/AAC-cards/illustration/verb/aac_laugh.png'),
('angry', '화나다', 'verb', '😠', 'muru-cards/AAC-cards/illustration/verb/aac_angry.png'),
('open', '열다', 'verb', '🚪', 'muru-cards/AAC-cards/illustration/verb/aac_open.png'),
('close', '닫다', 'verb', '🚪', 'muru-cards/AAC-cards/illustration/verb/aac_close.png'),
('wear', '입다', 'verb', '👕', 'muru-cards/AAC-cards/illustration/verb/aac_wear.png'),
('undress', '벗다', 'verb', '👕', 'muru-cards/AAC-cards/illustration/verb/aac_undress.png'),
('ride', '타다', 'verb', '🚌', 'muru-cards/AAC-cards/illustration/verb/aac_ride.png'),
('get_off', '내리다', 'verb', '🚌', 'muru-cards/AAC-cards/illustration/verb/aac_get_off.png'),
('give', '주다', 'verb', '🎁', 'muru-cards/AAC-cards/illustration/verb/aac_give.png'),
('receive', '받다', 'verb', '🎁', 'muru-cards/AAC-cards/illustration/verb/aac_receive.png'),
('buy', '사다', 'verb', '🛒', 'muru-cards/AAC-cards/illustration/verb/aac_buy.png'),
('sell', '팔다', 'verb', '💰', 'muru-cards/AAC-cards/illustration/verb/aac_sell.png'),
('make', '만들다', 'verb', '🔨', 'muru-cards/AAC-cards/illustration/verb/aac_make.png'),
('break', '부수다', 'verb', '🔨', 'muru-cards/AAC-cards/illustration/verb/aac_break.png'),
('cut', '자르다', 'verb', '✂️', 'muru-cards/AAC-cards/illustration/verb/aac_cut.png'),
('stick', '붙이다', 'verb', '🩹', 'muru-cards/AAC-cards/illustration/verb/aac_stick.png'),
('push', '밀다', 'verb', '👐', 'muru-cards/AAC-cards/illustration/verb/aac_push.png'),
('pull', '당기다', 'verb', '👐', 'muru-cards/AAC-cards/illustration/verb/aac_pull.png'),
('throw', '던지다', 'verb', '🥎', 'muru-cards/AAC-cards/illustration/verb/aac_throw.png'),
('catch', '잡다', 'verb', '🥎', 'muru-cards/AAC-cards/illustration/verb/aac_catch.png'),
('kick', '차다', 'verb', '🦶', 'muru-cards/AAC-cards/illustration/verb/aac_kick.png'),
('hit', '치다', 'verb', '👊', 'muru-cards/AAC-cards/illustration/verb/aac_hit.png'),
('see', '보다', 'verb', '👀', 'muru-cards/AAC-cards/illustration/verb/aac_see.png'),
('hear', '듣다', 'verb', '👂', 'muru-cards/AAC-cards/illustration/verb/aac_hear.png'),
('smell', '냄새맡다', 'verb', '👃', 'muru-cards/AAC-cards/illustration/verb/aac_smell.png'),
('taste', '맛보다', 'verb', '👅', 'muru-cards/AAC-cards/illustration/verb/aac_taste.png'),
('touch', '만지다', 'verb', '✋', 'muru-cards/AAC-cards/illustration/verb/aac_touch.png'),
('think', '생각하다', 'verb', '💭', 'muru-cards/AAC-cards/illustration/verb/aac_think.png'),
('know', '알다', 'verb', '💡', 'muru-cards/AAC-cards/illustration/verb/aac_know.png'),
('unknown', '모르다', 'verb', '❓', 'muru-cards/AAC-cards/illustration/verb/aac_unknown.png'),
('want', '원하다', 'verb', '🙏', 'muru-cards/AAC-cards/illustration/verb/aac_want.png'),
('help', '도와주다', 'verb', '🤝', 'muru-cards/AAC-cards/illustration/verb/aac_help.png')
ON CONFLICT (slug, category) DO NOTHING;
