-- IMPORTANT: Please Select ALL Text (Ctrl+A) and Run to avoid syntax errors
-- Add Verb (Action) Cards
-- Base path: muru-cards/AAC-cards/illustration/verb/

DELETE FROM public.aac_cards WHERE category = 'verb';

INSERT INTO public.aac_cards (slug, label, category, emoji, image_path) VALUES
('break_a_glass', '깨다(유리를)', 'verb', '🔨', 'muru-cards/AAC-cards/illustration/verb/aac_break_a_glass.png'),
('carry', '나르다', 'verb', '📦', 'muru-cards/AAC-cards/illustration/verb/aac_carry.png'),
('close', '닫다', 'verb', '🚪', 'muru-cards/AAC-cards/illustration/verb/aac_close.png'),
('cover', '덮다', 'verb', '🤲', 'muru-cards/AAC-cards/illustration/verb/aac_cover.png'),
('cross', '건너다', 'verb', '횡', 'muru-cards/AAC-cards/illustration/verb/aac_cross.png'),
('draw', '그리다', 'verb', '🎨', 'muru-cards/AAC-cards/illustration/verb/aac_draw.png'),
('enter', '들어가다', 'verb', '🚪', 'muru-cards/AAC-cards/illustration/verb/aac_enter.png'),
('fall_on_ones_back', '뒤로 넘어지다', 'verb', '🤸', 'muru-cards/AAC-cards/illustration/verb/aac_fall_on_back.png'),
('finish', '끝내다', 'verb', '🏁', 'muru-cards/AAC-cards/illustration/verb/aac_finish.png'),
('fix', '고치다', 'verb', '🔧', 'muru-cards/AAC-cards/illustration/verb/aac_fix.png'),
('fly', '날다', 'verb', '✈️', 'muru-cards/AAC-cards/illustration/verb/aac_fly.png'),
('go_around', '다니다', 'verb', '🚶', 'muru-cards/AAC-cards/illustration/verb/aac_go_around.png'),
('go_down', '내려가다', 'verb', '⬇️', 'muru-cards/AAC-cards/illustration/verb/aac_go_down.png'),
('go_out', '나가다', 'verb', '🚪', 'muru-cards/AAC-cards/illustration/verb/aac_go_out.png'),
('go', '가다', 'verb', '🚶', 'muru-cards/AAC-cards/illustration/verb/aac_go.png'),
('have', '가지다', 'verb', '🤲', 'muru-cards/AAC-cards/illustration/verb/aac_have.png'),
('help', '도와주다', 'verb', '🤝', 'muru-cards/AAC-cards/illustration/verb/aac_help.png'),
('hurt', '다치다', 'verb', '🤕', 'muru-cards/AAC-cards/illustration/verb/aac_hurt.png'),
('insert', '넣다(삽입)', 'verb', '📥', 'muru-cards/AAC-cards/illustration/verb/aac_insert.png'),
('knock', '노크하다', 'verb', '✊', 'muru-cards/AAC-cards/illustration/verb/aac_knock.png'),
('lie', '눕다', 'verb', '🛌', 'muru-cards/AAC-cards/illustration/verb/aac_lie.png'),
('lift', '들다', 'verb', '🏋️', 'muru-cards/AAC-cards/illustration/verb/aac_lift.png'),
('listen', '듣다', 'verb', '👂', 'muru-cards/AAC-cards/illustration/verb/aac_listen.png'),
('peel', '껍질 벗기다', 'verb', '🍌', 'muru-cards/AAC-cards/illustration/verb/aac_peel.png'),
('place', '놓다', 'verb', '📍', 'muru-cards/AAC-cards/illustration/verb/aac_place.png'),
('play', '놀다', 'verb', '🛝', 'muru-cards/AAC-cards/illustration/verb/aac_play.png'),
('point', '가리키다', 'verb', '👉', 'muru-cards/AAC-cards/illustration/verb/aac_point.png'),
('press', '누르다', 'verb', '👇', 'muru-cards/AAC-cards/illustration/verb/aac_press.png'),
('pull_fixed', '당기다(고정)', 'verb', '🔒', 'muru-cards/AAC-cards/illustration/verb/aac_pull_fixed.png'),
('pull_out', '빼다', 'verb', '📤', 'muru-cards/AAC-cards/illustration/verb/aac_pull_out.png'),
('pull', '당기다', 'verb', '👐', 'muru-cards/AAC-cards/illustration/verb/aac_pull.png'),
('put_in_candle', '초를 꽂다', 'verb', '🎂', 'muru-cards/AAC-cards/illustration/verb/aac_put_in_candle_.png'),
('put_in', '넣다', 'verb', '📥', 'muru-cards/AAC-cards/illustration/verb/aac_put_in.png'),
('run', '뛰다', 'verb', '🏃', 'muru-cards/AAC-cards/illustration/verb/aac_run.png'),
('share', '나누다', 'verb', '🍰', 'muru-cards/AAC-cards/illustration/verb/aac_share.png'),
('sing', '노래하다', 'verb', '🎤', 'muru-cards/AAC-cards/illustration/verb/aac_sing.png'),
('snap', '끊어지다', 'verb', '🫰', 'muru-cards/AAC-cards/illustration/verb/aac_snap.png'),
('spin', '돌다(회전)', 'verb', '😵‍💫', 'muru-cards/AAC-cards/illustration/verb/aac_spin.png'),
('study', '공부하다', 'verb', '📚', 'muru-cards/AAC-cards/illustration/verb/aac_study.png'),
('throw', '던지다', 'verb', '🥎', 'muru-cards/AAC-cards/illustration/verb/aac_throw.png'),
('tickle', '간지럽히다', 'verb', '🪶', 'muru-cards/AAC-cards/illustration/verb/aac_tickle.png'),
('turn_off', '끄다', 'verb', '📴', 'muru-cards/AAC-cards/illustration/verb/aac_turn_off.png'),
('turn', '돌다', 'verb', '🔄', 'muru-cards/AAC-cards/illustration/verb/aac_turn.png'),
('wait_stay', '기다리다(머뭄)', 'verb', '⏳', 'muru-cards/AAC-cards/illustration/verb/aac_wait_stay.png'),
('wait_stop', '기다리다(멈춤)', 'verb', '🛑', 'muru-cards/AAC-cards/illustration/verb/aac_wait_stop.png'),
('walk', '걷다', 'verb', '🚶', 'muru-cards/AAC-cards/illustration/verb/aac_walk.png'),
('wipe', '닦다', 'verb', '🧽', 'muru-cards/AAC-cards/illustration/verb/aac_wipe.png')
ON CONFLICT (slug, category) DO UPDATE 
SET image_path = EXCLUDED.image_path,
    label = EXCLUDED.label,
    emoji = EXCLUDED.emoji;